name: Compile Static Libraries

on:
    workflow_dispatch:
    push:

jobs:
    compile:
      if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]') }}
      strategy:
        matrix:
          include:
            - runner: ubuntu-24.04-arm
              architecture: aarch64
              abi: arm64-v8a
              image: termux/termux-docker:aarch64
            - runner: ubuntu-24.04
              architecture: x86_64
              abi: x86_64
              image: termux/termux-docker:x86_64

      runs-on: ${{ matrix.runner }}
      container:
        image: ${{ matrix.image }}
        volumes:
          - /tmp/node20:/__e/node20

      env:
        ANDROID_ROOT: /system
        ANDROID_DATA: /data
        PREFIX: /data/data/com.termux/files/usr
        HOME: /data/data/com.termux/files/home
        PATH: /data/data/com.termux/files/usr/bin
        TMPDIR: /data/data/com.termux/files/usr/tmp
        LANG: en_US.UTF-8
        TZ: UTC

      steps:
        - name: Install dependencies
          run: |
            ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
            /entrypoint.sh bash -c "yes | pkg upgrade -y"
            chmod -R o+x ${PREFIX}/bin
            /entrypoint.sh pkg install -y php clang binutils

        - name: Checkout repository
          uses: actions/checkout@main

        - name: Compile files
          run: php scripts/compile.php clang

        - name: Compile static libraries
          run: ar r int/*.o ./plutostaticlibrary-${{ matrix.abi }}.a

        - name: Upload libraries
          uses: actions/upload-artifact@v4
          with:
            name: plutostaticlibrary-${{ matrix.abi }}.a
            path: ./plutostaticlibrary-${{ matrix.abi }}.a
