name: Build Docker image
on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: |
            ghcr.io/plutolang/pluto:latest
            ghcr.io/plutolang/pluto:${{ github.event.release.tag_name }}
